// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/store/providor/Store_providor";

import { Navbar, Footer, Toast } from "@/componets/comon/index";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en" data-theme="dark">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased container mx-auto`}
        >
          <Navbar />
          {children}
          <Footer />
          <Toast />
        </body>
      </html>
    </StoreProvider>
  );
}
